import os
import time

# colors for ascii art characters
ANSI_RED = u"\u001b[31m"
ANSI_YELLOW           = u"\u001B[33m"
ANSI_BLUE_BACK        = u"\u001B[44m"
RESET_COLOR = u"\u001B[0m\u001B[2D"

# variable used to check if alive/if lives > 0
def checkIfAlive():
  lives = int(open("variables/lives.txt").read())
  if(lives > 0): 
    print("You have " + open("variables/lives.txt").read() + " lives\n")
    
  else: 
    print("You run out of lives")
    #print(" _____ ____  _      _____   ____  _     _____ ____") 
    #print("/  __//  _ \/ \__/|/  __/  /  _ \/ \ |\/  __//  __\ ")
    #print("| |  _| / \|| |\/|||  \    | / \|| | //|  \  |  \/|")
    #print("| |_//| |-||| |  |||  /_   | \_/|| \// |  /_ |    /")
    #print("\____\\_/ \|\_/  \|\____\  \____/\__/  \____\\_/\_\ ")
    #print("                                               ")
    
    print(ANSI_RED, " _____              __  __   ______   ")
    print(" / ____|     /\     |  \/  | |  ____|  ")
    print("| |  __     /  \    | \  / | | |__     ")
    print("| | |_ |   / /\ \   | |\/| | |  __|    ")
    print("| |__| |  / ____ \  | |  | | | |____   ")
    print(" \_____| /_/    \_\ |_|  |_| |______|  \n")
    print("  ____   __      __  ______   _____    ")
    print(" / __ \  \ \    / / |  ____| |  __ \   ")
    print("| |  | |  \ \  / /  | |__    | |__) |  ")
    print("| |  | |   \ \/ /   |  __|   |  _  /   ")
    print("| |__| |    \  /    | |____  | | \ \   ")
    print(" \____/      \/     |______| |_|  \_\  ")
    time.sleep(1)
    exit()


def cls():
    os.system('cls' if os.name=='nt' else 'clear')

def addLives(numberToAdd):
  current = int(open("variables/lives.txt").read())
  total = str(current + numberToAdd)
  open("variables/lives.txt", "w").write(total)
  
def setLives(numbOfLives):
  open("variables/lives.txt", "w").write(numbOfLives)
def writeFile(file, stuffToWrite):
  open(file, "w").write(str(stuffToWrite))

def printDoorway():
  print("╔═══════════════════════════════════════════════════════════════════╗")
  print("║.._|      | `-.  | `.  -_-_ _-_  _-  _- -_ -  .'|   |.'|     |  _..║")
  print("║   `-.._  |    |`!  |`.  -_ -__ -_ _- _-_-  .'  |.;'   |   _.!-'|  ║")
  print("║      | `-!._  |  `;!  ;. _______________ ,'| .-' |   _!.|'     |  ║")
  print("║..__  |     |`-!._ | `.| |_______________||.'|   _!.;'   |     _|..║")
  print("║   |`` ..__ |    |` ;.|  |_|███████████|_|'|._!-|   |   _|..-|'    ║")
  print("║   |      |``--..|_ | `;!|_|███████████|_|.'    |_..!-'|     |     ║")
  print("║   |      |    |   |`-,!_|_|███████████|_||.!--'  |    |     |     ║")
  print("║___|______|____!.,.!,.!,!|_|███████████|_|,!,.!.,.!..__|_____|_____║")
  print("║      |     |    |  |  | |_|███████████|_|| |   |   |    |      |  ║")
  print("║      |     |    |..!-;''|_|███████████|_| |`-..|   |    |      |  ║")
  print("║      |    _!.-''  | _!,'|_|███████████|_||!._|  `'-!.._ |      |  ║")
  print("║     _!.-'|    | _.'|  !;|_|███████████|_|`.| `-._|    |``-.._  |  ║")
  print("║..-''     |  _.''|  !-| !|_|███████████|_|.|`-. | ``._ |     |``...║")
  print("║   |      |.|    |.|  !| |_|███████████|_||`. |`!   | `..    |     ║")
  print("║   |  _.-'  |  .'  |.' |/|_|███████████|_|! |`!  `,.|    |-._|     ║")
  print("║  _!'''|    !.'|  .'| .'|[@]███████████[@] \|  `. | `._  |   `-._  ║")
  print("║-'    |   .'   |.|  |/| /                 \|`.  |`!    |.|      |`-║")
  print("║      |_.'|   .' | .' |/                   \  \ |  `.  | `._-   |  ║")
  print("║     .'   | .'   |/|  /                     \ |`!   |`.|    `.  |  ║")
  print("║  _.'     !'|   .' | /                       \|  `  |  `.    |`.|  ║")
  print("╚═══════════════════════════════════════════════════════════════════╝")

def printSkull():
  print("                          ,--.")
  print("                          {    }")
  print("                          K,   }")
  print("                        /  `Y`")
  print("                    _   /   /")
  print("                  {_'-K.__/")
  print("                    `/-.__L._")
  print("                    /  ' /`\_}")
  print("                    /  ' /     ")
  print("            ____   /  ' /")
  print("    ,-'~~~~    ~~/  ' /_")
  print("  ,'             ``~~~%%',")
  print("  (                     %  Y")
  print("{                      %% I")
  print("{      -                 %  `.")
  print("|       ',                %  )")
  print("|        |   ,..__      __. Y")
  print("|    .,_./  Y ' / ^Y   J   )|")
  print("\           |' /   |   |   ||")
  print("\          L_/    . _ (_,.'(")
  print("  \,   ,      ^^""' / |      )")
  print("    \_  \          /,L]     /")
  print("      '-_`-,       ` `   ./`")
  print("        `-(_            )")
  print("            ^^\..___,.--`")

def printIntro():
  print(ANSI_RED,"  /_/-----/_/|", ANSI_YELLOW, "   __    ")
  print(ANSI_RED,"  ( ( ' ' ( (|",ANSI_YELLOW," /'--'\    ")
  print(ANSI_RED,"  (_( ' ' (_(|",ANSI_YELLOW,"/.    .\   ")
  print(ANSI_RED,"  / /=====/ /|",ANSI_YELLOW,"  '||'     ")
  print(ANSI_RED," /_//____/_/ |",ANSI_YELLOW,"   ||      ")
  print(ANSI_RED,"(o|:.....|o) |",ANSI_YELLOW,"   ||      ")
  print(ANSI_RED,"|_|:_____|_|/'",ANSI_YELLOW,"  _||_     ")
  print(ANSI_RED," '        '   ",ANSI_YELLOW," /____\    ")
  print(RESET_COLOR)
  print(" ")

def printPuzzle(): 
  print ()


def printClock():
  os.system('cls' if os.name=='nt' else 'clear')
  ANSI_YELLOW           = u"\u001B[33m\u001B[2D"
  RESET_COLOR = u"\u001B[0m\u001B[2D"
  ANSI_HOME_CURSOR = u"\u001B[0;0H\u001B[2D"
  print(ANSI_YELLOW)
  print()
  print("           (_)           ")
  print("         _ )_( _         ")
  print("       /`_) H (_`\       ")
  print("     .' (  { }  ) '.     ")
  print("   _/ /` '-'='-' `\ \_   ")
  print("  [_.'    _,...,_   '._] ")
  print("   |   .:^      ^:.   |  ")
  print("   |__//_________\\\__|   ")
  print("    | .-----------. |    ")
  print("    | |   _..._   | |    ")
  print("    | | /    /  \ | |    ")
  print("    | ||-   <   -|| |    ")
  print("    | | \    \  / | |    ")
  print("    | |[`'-...-'`]| |    ")
  print("    | | ;-.___.-; | |    ")
  print("    | | |  |||  | | |    ")
  print("    | | |  |||  | | |    ")
  print("    | | |  |||  | | |    ")
  print("    | | |  |||  | | |    ")
  print("    | | |  |||  | | |    ")
  print("    | | | _|||_ | | |    ")
  print("    | | | >===< | | |    ")
  print("    | | | |___| | | |    ")
  print("    | | |  |||  | | |    ")
  print("    | | |  ;-;  | | |    ")
  print("    | | | (   ) | | |    ")
  print("    | | |  '-'  | | |    ")
  print("    | | '-------' | |    ")
  print("   _| '-----------' |_   ")
  print("  [= === === ==== == =]  ")
  print("  [__--__--___--__--__]  ")
  print(" /__-___-___-___-___-__\ ")
  print( "`^^^^^^^^^^^^^^^^^^^^^^`")
  time.sleep(0.15)
  print(ANSI_HOME_CURSOR)
  #os.system('cls' if os.name=='nt' else 'clear')
  print("")
  print("           (_)           ")
  print("         _ )_( _         ")
  print("       /`_) H (_`\       ")
  print("     .' (  { }  ) '.     ")
  print("   _/ /` '-'='-' `\ \_   ")
  print("  [_.'    _,...,_   '._] ")
  print("   |   .:^      ^:.   |  ")
  print("   |__//_________\\\__|   ")
  print("    | .-----------. |    ")
  print("    | |   _..._   | |    ")
  print("    | | /    /  \ | |    ")
  print("    | ||-   <   -|| |    ")
  print("    | | \    \  / | |    ")
  print("    | |[`'-...-'`]| |    ")
  print("    | | ;-.___.-; | |    ")
  print("    | | | ///   | | |    ")
  print("    | | | |/|   | | |    ")
  print("    | | | ///   | | |    ")
  print("    | | | |/|   | | |    ")
  print("    | | | ///   | | |    ")
  print("    | | ||/|_   | | |    ")
  print("    | | |==<    | | |    ")
  print("    | | |_|     | | |    ")
  print("    | | ||      | | |    ")
  print("    | | |;      | | |    ")
  print("    | | |       | | |    ")
  print("    | | |       | | |    ")
  print("    | | '-------' | |    ")
  print("   _| '-----------' |_   ")
  print("  [= === === ==== == =]  ")
  print("  [__--__--___--__--__]  ")
  print(" /__-___-___-___-___-__\ ")
  print( "`^^^^^^^^^^^^^^^^^^^^^^`")
  time.sleep(0.15)
  print(ANSI_HOME_CURSOR)
  #os.system('cls' if os.name=='nt' else 'clear')
  print("")
  print("           (_)           ")
  print("         _ )_( _         ")
  print("       /`_) H (_`\       ")
  print("     .' (  { }  ) '.     ")
  print("   _/ /` '-'='-' `\ \_   ")
  print("  [_.'    _,...,_   '._] ")
  print("   |   .:^      ^:.   |  ")
  print("   |__//_________\\\__|   ")
  print("    | .-----------. |    ")
  print("    | |   _..._   | |    ")
  print("    | | /    /  \ | |    ")
  print("    | ||-   <   -|| |    ")
  print("    | | \    \  / | |    ")
  print("    | |[`'-...-'`]| |    ")
  print("    | | ;-.___.-; | |    ")
  print("    | | |///    | | |    ")
  print("    | | |//     | | |    ")
  print("    | | |/      | | |    ")
  print("    | | |       | | |    ")
  print("    | | |       | | |    ")
  print("    | | |       | | |    ")
  print("    | | |       | | |    ")
  print("    | | |       | | |    ")
  print("    | | |       | | |    ")
  print("    | | |       | | |    ")
  print("    | | |       | | |    ")
  print("    | | |       | | |    ")
  print("    | | '-------' | |    ")
  print("   _| '-----------' |_   ")
  print("  [= === === ==== == =]  ")
  print("  [__--__--___--__--__]  ")
  print(" /__-___-___-___-___-__\ ")
  print( "`^^^^^^^^^^^^^^^^^^^^^^`")
  time.sleep(0.15)
  print(ANSI_HOME_CURSOR)
  #os.system('cls' if os.name=='nt' else 'clear')
  print("")
  print("           (_)           ")
  print("         _ )_( _         ")
  print("       /`_) H (_`\       ")
  print("     .' (  { }  ) '.     ")
  print("   _/ /` '-'='-' `\ \_   ")
  print("  [_.'    _,...,_   '._] ")
  print("   |   .:^      ^:.   |  ")
  print("   |__//_________\\\__|   ")
  print("    | .-----------. |    ")
  print("    | |   _..._   | |    ")
  print("    | | /    /  \ | |    ")
  print("    | ||-   <   -|| |    ")
  print("    | | \    \  / | |    ")
  print("    | |[`'-...-'`]| |    ")
  print("    | | ;-.___.-; | |    ")
  print("    | | | ///   | | |    ")
  print("    | | | |/|   | | |    ")
  print("    | | | ///   | | |    ")
  print("    | | | |/|   | | |    ")
  print("    | | | ///   | | |    ")
  print("    | | ||/|_   | | |    ")
  print("    | | |==<    | | |    ")
  print("    | | |_|     | | |    ")
  print("    | | ||      | | |    ")
  print("    | | |;      | | |    ")
  print("    | | |       | | |    ")
  print("    | | |       | | |    ")
  print("    | | '-------' | |    ")
  print("   _| '-----------' |_   ")
  print("  [= === === ==== == =]  ")
  print("  [__--__--___--__--__]  ")
  print(" /__-___-___-___-___-__\ ")
  print( "`^^^^^^^^^^^^^^^^^^^^^^`")
  time.sleep(0.15)
  print(ANSI_HOME_CURSOR)
  #os.system('cls' if os.name=='nt' else 'clear')
  print("")
  print("           (_)           ")
  print("         _ )_( _         ")
  print("       /`_) H (_`\       ")
  print("     .' (  { }  ) '.     ")
  print("   _/ /` '-'='-' `\ \_   ")
  print("  [_.'    _,...,_   '._] ")
  print("   |   .:^      ^:.   |  ")
  print("   |__//_________\\\__|   ")
  print("    | .-----------. |    ")
  print("    | |   _..._   | |    ")
  print("    | | /    /  \ | |    ")
  print("    | ||-   <   -|| |    ")
  print("    | | \    \  / | |    ")
  print("    | |[`'-...-'`]| |    ")
  print("    | | ;-.___.-; | |    ")
  print("    | | |    \\\\\| | |    ")
  print("    | | |   |\| | | |    ")
  print("    | | |   \\\\\ | | |    ")
  print("    | | |   |\| | | |    ")
  print("    | | |   \\\\\ | | |    ")
  print("    | | |   _|\|| | |    ")
  print("    | | |    >==| | |    ")
  print("    | | |     |_| | |    ")
  print("    | | |      || | |    ")
  print("    | | |      ;| | |    ")
  print("    | | |       | | |    ")
  print("    | | |       | | |    ")
  print("    | | '-------' | |    ")
  print("   _| '-----------' |_   ")
  print("  [= === === ==== == =]  ")
  print("  [__--__--___--__--__]  ")
  print(" /__-___-___-___-___-__\ ")
  print( "`^^^^^^^^^^^^^^^^^^^^^^`")
  time.sleep(0.15)
  print(ANSI_HOME_CURSOR)
  #os.system('cls' if os.name=='nt' else 'clear')
  print("")
  print("           (_)           ")
  print("         _ )_( _         ")
  print("       /`_) H (_`\       ")
  print("     .' (  { }  ) '.     ")
  print("   _/ /` '-'='-' `\ \_   ")
  print("  [_.'    _,...,_   '._] ")
  print("   |   .:^      ^:.   |  ")
  print("   |__//_________\\\__|   ")
  print("    | .-----------. |    ")
  print("    | |   _..._   | |    ")
  print("    | | /    /  \ | |    ")
  print("    | ||-   <   -|| |    ")
  print("    | | \    \  / | |    ")
  print("    | |[`'-...-'`]| |    ")
  print("    | | ;-.___.-; | |    ")
  print("    | | |   \\\\\ | | |    ")
  print("    | | |   \\\\\ | | |    ")
  print("    | | |    \\\\\| | |    ")
  print("    | | |     \\\| | |    ")
  print("    | | |      \| | |    ")
  print("    | | |       | | |    ")
  print("    | | |       | | |    ")
  print("    | | |       | | |    ")
  print("    | | |       | | |    ")
  print("    | | |       | | |    ")
  print("    | | |       | | |    ")
  print("    | | |       | | |    ")
  print("    | | '-------' | |    ")
  print("   _| '-----------' |_   ")
  print("  [= === === ==== == =]  ")
  print("  [__--__--___--__--__]  ")
  print(" /__-___-___-___-___-__\ ")
  print( "`^^^^^^^^^^^^^^^^^^^^^^`")
  time.sleep(0.15)
  print(ANSI_HOME_CURSOR)
  #os.system('cls' if os.name=='nt' else 'clear')
  print("")
  print("           (_)           ")
  print("         _ )_( _         ")
  print("       /`_) H (_`\       ")
  print("     .' (  { }  ) '.     ")
  print("   _/ /` '-'='-' `\ \_   ")
  print("  [_.'    _,...,_   '._] ")
  print("   |   .:^      ^:.   |  ")
  print("   |__//_________\\\__|   ")
  print("    | .-----------. |    ")
  print("    | |   _..._   | |    ")
  print("    | | /    /  \ | |    ")
  print("    | ||-   <   -|| |    ")
  print("    | | \    \  / | |    ")
  print("    | |[`'-...-'`]| |    ")
  print("    | | ;-.___.-; | |    ")
  print("    | | |   \\\\\ | | |    ")
  print("    | | |   |\| | | |    ")
  print("    | | |   \\\\\ | | |    ")
  print("    | | |   |\| | | |    ")
  print("    | | |   \\\\\ | | |    ")
  print("    | | |   _|\|| | |    ")
  print("    | | |    >==| | |    ")
  print("    | | |     |_| | |    ")
  print("    | | |      || | |    ")
  print("    | | |      ;| | |    ")
  print("    | | |       | | |    ")
  print("    | | |       | | |    ")
  print("    | | '-------' | |    ")
  print("   _| '-----------' |_   ")
  print("  [= === === ==== == =]  ")
  print("  [__--__--___--__--__]  ")
  print(" /__-___-___-___-___-__\ ")
  print( "`^^^^^^^^^^^^^^^^^^^^^^`")

def print69():
  def small():
    print(" ")
    print("69")
  def normal():
    print(" _   _")  
    print("|_  |_|") 
    print("|_|  _|")
  def big():
    print(" ____     ____")
    print("/        /    |")
    print("|____    \____|")
    print("|    \        |")
    print("\____/    ____/")

  whichPrint = {
    1: small,
    2: normal,
    3: big,
    4: normal,
    5: small
  }
  for i in range(5):
    global printSize
    printSize = 1
    for i in range(5):
      for key, value in whichPrint.items():
        if printSize == key:
          printOne = value

      def printLoop():
        os.system('cls' if os.name=='nt' else 'clear')
        printOne()
        time.sleep(0.15)

      printLoop()
      printSize = printSize + 1




